name: main
on:
  push:
    branches:
    - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:${{ github.sha }}
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
      working-directory: ./.github/workflows
    - name: Release to GitHub
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_AUTHOR_NAME: vitor-caetano  
        GIT_AUTHOR_EMAIL: vitor.e.caetano@gmail.com
        GIT_COMMITTER_NAME: vitor-caetano
        GIT_COMMITTER_EMAIL: vitor.e.caetano@gmail.com
      run: npx semantic-release
